### ISSUE TITLE
FAILED

### ISSUE THREAD

**Issue by dominicusin** [Zlopez/ansible_HTPC#3]
TASK [Add the flathub flatpak repository remote to the user installation] *****************************************************************************************************************************************
fatal: [tv13]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 192.168.1.146 closed.\r\n", "module_stdout": "/root/.ansible/tmp/ansible-tmp-1550830467.4875815-43436990123332/AnsiballZ_flatpak_remote.py:17: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses\r\n  import imp\r\nTraceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1550830467.4875815-43436990123332/AnsiballZ_flatpak_remote.py\", line 113, in <module>\r\n    _ansiballz_main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1550830467.4875815-43436990123332/AnsiballZ_flatpak_remote.py\", line 105, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/root/.ansible/tmp/ansible-tmp-1550830467.4875815-43436990123332/AnsiballZ_flatpak_remote.py\", line 48, in invoke_module\r\n    imp.load_module('__main__', mod, module, MOD_DESC)\r\n  File \"/usr/lib64/python3.7/imp.py\", line 234, in load_module\r\n    return load_source(name, filename, file)\r\n  File \"/usr/lib64/python3.7/imp.py\", line 169, in load_source\r\n    module = _exec(spec, sys.modules[name])\r\n  File \"<frozen importlib._bootstrap>\", line 630, in _exec\r\n  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\r\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\r\n  File \"/tmp/ansible_flatpak_remote_payload_sqzyoy0k/__main__.py\", line 241, in <module>\r\n  File \"/tmp/ansible_flatpak_remote_payload_sqzyoy0k/__main__.py\", line 230, in main\r\n  File \"/tmp/ansible_flatpak_remote_payload_sqzyoy0k/__main__.py\", line 172, in remote_exists\r\nIndexError: list index out of range\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
	to retry, use: --limit @/home

**Comment by Zlopez** [comment]
This looks like you have version of ansible, that doesn't support `flatpak_remote` module or has some bug in it.

Try to update ansible to newer version.
